# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: equity-sos-go
  labels:
    app: equity-sos-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equity-sos-go
  template:
    metadata:
      labels:
        app: equity-sos-go
    spec:
      containers:
      - name: equity-sos-go
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true